version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 767397907272.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo "Build started on date"
      - echo "Building the Docker image..."
      - docker build -t python-flask-aws-beanstalk-api .
      - docker tag python-flask-aws-beanstalk-api:latest 767397907272.dkr.ecr.us-east-2.amazonaws.com/python-flask-aws-beanstalk-api:latest
  post_build:
    commands:
      - echo "Build completed on date"
      - echo "Pushing the Docker image..."
      - docker push 767397907272.dkr.ecr.us-east-2.amazonaws.com/python-flask-aws-beanstalk-api:latest
artifacts:
  files:
    - '**/*'