version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask-aws-beanstalk-api
    restart: always
    volumes:
      - ".:/app"
    env_file:
      - .env
    ports:
      - "5000:5000"
    tty: true